project_id = "zifoxagxzysuickngzdy"

[functions.ocr-extract]
verify_jwt = false

[functions.generate-prescription-pdf]
verify_jwt = false

[functions.generate-certificate-pdf]
verify_jwt = false

[functions.auth-pin]
verify_jwt = false
